const display = document.getElementById('display');
const context = display.getContext('2d');
const width = 420;
const height = 420;
const pixelSize = 10;
var snakeBody = [];
var snakeLength;
var directionX;
var directionY;
var mandu = {};
const startBtn = document.getElementById('startBtn');
const restartBtn = document.getElementById('restartBtn');
const submitBtn = document.getElementById('submitBtn');
var score = 0;
var sound = document.getElementById("audio");